const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const config = require('./setup/config.cjs');
const native = require('./setup/native.cjs');
const lifecycle = require('./setup/lifecycle.cjs');
const args = process.argv.slice(2);
const callerDirectory = process.cwd();
const command = args[0];
function option(name) { const at = args.indexOf(name); if(at === -1)return undefined; if(!args[at + 1] || args[at + 1].startsWith('--'))throw Error('Valore richiesto per ' + name); return args[at + 1]; }
async function status() {
  const envs = config.readAll(), journal = config.state();
  console.log('MODE=' + journal.mode);
  for (const role of config.roles) console.log(role.toUpperCase() + '_WALLET=' + (fs.existsSync(config.walletPath(envs[role], role)) ? 'present' : 'missing'));
  for (const role of config.roles) console.log(role.toUpperCase() + '_DID=' + (envs[role].DID_ID || 'not-set'));
  console.log('SCHEMA_ID=' + (envs.provider.SCHEMA_ID || 'not-set'));
  console.log('CREDENTIAL_DEFINITION_ID=' + (envs.provider.CREDENTIAL_DEFINITION_ID || 'not-set'));
  console.log('COSMOS_PAYER_ADDRESS=' + await native.payerAddress(envs.issuer.ISSUER_COSMOS_SEED));
  for (const [name, value] of Object.entries(journal.operations)) console.log(name + '=' + value.status);
  if (envs.issuer.CHEQD_RESOURCE_FEE_NCHEQ) console.log('RESOURCE_FEE_NCHEQ=' + envs.issuer.CHEQD_RESOURCE_FEE_NCHEQ);
}
async function main() {
  if (!['init', 'wallets', 'publish', 'status', 'inspect', 'unlock'].includes(command)) throw Error('Uso: node integrations/setup.cjs init [--payer-file FILE] | wallets | publish [--retry-pending] | status | inspect | unlock');
  const extra = args.slice(1);
  const valid = extra.length === 0 || (command === 'init' && extra.length === 2 && extra[0] === '--payer-file' && !extra[1].startsWith('--')) || (command === 'publish' && extra.length === 1 && extra[0] === '--retry-pending');
  if (!valid) throw Error('Argomenti non riconosciuti: usare init [--payer-file FILE] oppure publish [--retry-pending]; gli altri comandi non accettano opzioni.');
  require('./verify-originals.cjs').verify();
  process.chdir(__dirname);
  if (command === 'init') {
    const seedFile = option('--payer-file');
    const payerMnemonic = seedFile ? fs.readFileSync(path.resolve(callerDirectory, seedFile), 'utf8').trim() : undefined;
    config.initialize({ payerMnemonic });
    console.log('CONFIG_CREATED: nessun wallet creato e nessuna transazione inviata.');
    await status(); return;
  }
  if (command === 'status') return status();
  if (command === 'inspect') {
    const release=config.lock();let session;
    try {
      const envs=config.readAll();config.validate(envs);
      if(!fs.existsSync(config.walletPath(envs.issuer,'issuer')))throw Error('Wallet Issuer assente: nessun wallet creato.');
      session=await native.openAgent('issuer',envs.issuer);
      const schemaId=await native.inspectIssuer(session.agent,envs.issuer);
      for(const role of ['provider','issuer']){envs[role].SCHEMA_ID=schemaId;config.atomic(path.join(config.DEFAULT_DIRECTORY,role+'.env'),config.encode(envs[role]));}
      console.log('ISSUER_RESOURCES_VERIFIED=true');console.log('SCHEMA_ID='+schemaId);
    }finally{if(session)await session.close();release();}
    return;
  }
  if (command === 'unlock') {
    const file = path.join(config.DEFAULT_DIRECTORY, '.setup.lock');
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (data.host !== os.hostname()) throw Error('Lock creato su un altro host: verificarlo su quella macchina.');
    let exists = true;
    try { process.kill(data.pid, 0); } catch (e) { if(e.code === 'ESRCH')exists = false; else throw e; }
    if (exists) throw Error('Il processo di setup risulta ancora attivo.');
    fs.unlinkSync(file); console.log('STALE_LOCK_REMOVED'); return;
  }
  const release = config.lock();
  try {
    if (command === 'wallets') { await lifecycle.wallets(); console.log('WALLETS_READY: nessuna transazione blockchain.'); }
    else {
      console.log('Pubblicazione su TESTNET: DID e risorse mancanti; usa i fondi del pagatore configurato.');
      if(args.includes('--retry-pending'))console.log('Ripetizione esplicita di operazioni incerte: può creare risorse aggiuntive e consumare fondi testnet.');
      await lifecycle.publish({ retryPending: args.includes('--retry-pending') });
      console.log('RESOURCES_READY: ora avvia Issuer e Holder per emettere la credenziale.');
    }
  } finally { release(); }
}
main().catch(error => {
  // Native / SDK error messages can embed payloads. Only errors generated by this setup are printed.
  const internal = String(error.stack || '').split('\n')[1] || '';
  if (internal.includes(path.sep + 'setup') && !internal.includes('node_modules')) console.error(error.message);
  else console.error('SETUP_FAILED: controlla dipendenze native, configurazione, wallet e accesso RPC. Nessun segreto mostrato.');
  process.exitCode = 1;
});
